openapi: 3.1.0
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /create-game:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name of the game creator
                categories:
                  type: array
                  description: The selected question categories
                  items:
                    type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
                description: Game ID
        "400":
          description: Game ID Missing
        "500":
          description: Server Fehler

  /join-game/{game-id}:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: string
              description: name of the person whom wants to join
      parameters:
        - name: game-id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
                description: sessionId
        "500":
          description: Server error

  /question/current:
    get:
      parameters:
        - name: sessionId
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: id
                  question:
                    type: string
                  answers:
                    type: array
                    items:
                      type: string
        "400":
          description: Invalid Session
        "500":
          description: Server error

  /submit-answer:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sessionId:
                  type: string
                selectedAnswer:
                  type: long
                  description: the id of the selected answer of the current question

  /leave-game:
    post:
      parameters:
        - name: sessionId
          in: query
          schema:
            type: string
          required: true
      responses:
        "200":
          description: OK
        "404":
          description: Session ID not found

  /scores/{gameID}:
    get:
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    score:
                      type: int
